# Generated by Django 2.2.28 on 2024-07-24 11:32

from django.db import migrations, models
import django.db.models.deletion
import fernet_fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forms', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='ACGReimbursementForm',
            fields=[
                ('form_id', models.AutoField(primary_key=True, serialize=False)),
                ('submitter', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('amount', models.CharField(max_length=20)),
                ('reimbursement_type', models.IntegerField(choices=[(1, 'Standard'), (2, 'Internal'), (3, 'Large')], default=1)),
                ('rejected', models.BooleanField(default=False)),
                ('name_on_account', models.CharField(max_length=100, null=True)),
                ('account_number', fernet_fields.fields.EncryptedCharField(blank=True, max_length=8, null=True, verbose_name='Account Number')),
                ('sort_code', fernet_fields.fields.EncryptedCharField(blank=True, max_length=6, null=True, verbose_name='Sort Code')),
                ('jcr_treasurer_approved', models.BooleanField(default=False)),
                ('jcr_treasurer_comments', models.TextField(blank=True)),
                ('jcr_treasurer_name', models.CharField(max_length=100)),
                ('jcr_treasurer_date', models.DateField(null=True)),
                ('senior_treasurer_approved', models.BooleanField(default=False)),
                ('senior_treasurer_comments', models.TextField(blank=True)),
                ('senior_treasurer_name', models.CharField(max_length=100)),
                ('senior_treasurer_date', models.DateField(null=True)),
                ('assistant_bursar_approved', models.BooleanField(default=False)),
                ('assistant_bursar_comments', models.TextField(blank=True)),
                ('assistant_bursar_name', models.CharField(max_length=100, null=True)),
                ('assistant_bursar_date', models.DateField(null=True)),
                ('bursary_paid', models.BooleanField(default=False)),
                ('bursary_date', models.DateField(null=True)),
                ('organization', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='forms.Organization')),
            ],
        ),
        migrations.CreateModel(
            name='ACGReimbursementFormReceiptEntry',
            fields=[
                ('entry_id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(null=True, upload_to='')),
                ('form', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='dcac.ACGReimbursementForm')),
            ],
        ),
        migrations.CreateModel(
            name='ACGReimbursementFormItemEntry',
            fields=[
                ('entry_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('amount', models.CharField(max_length=20)),
                ('fund_source', models.IntegerField(choices=[(1, 'Annual Consumable Grant'), (2, 'Depreciation Fund')], default=1)),
                ('form', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='dcac.ACGReimbursementForm')),
            ],
        ),
    ]
