# Generated by Django 2.2.28 on 2024-07-24 11:32

import budget.models
from django.db import migrations, models
import django.db.models.deletion
import fernet_fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forms', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('budget_id', models.AutoField(primary_key=True, serialize=False)),
                ('submitted', models.BooleanField(default=False)),
                ('approved', models.BooleanField(default=False)),
                ('year', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('submitter', models.CharField(max_length=10)),
                ('amount_acg', models.CharField(default='0', max_length=20)),
                ('amount_dep', models.CharField(default='0', max_length=20)),
                ('president', models.CharField(max_length=100, verbose_name='President')),
                ('president_crsid', budget.models.CRSidField(max_length=10, verbose_name='CRSid')),
                ('treasurer', models.CharField(max_length=100, verbose_name='Treasurer')),
                ('treasurer_crsid', budget.models.CRSidField(max_length=10, verbose_name='CRSid')),
                ('active_members', models.PositiveIntegerField(default=0, verbose_name='Number of Active Members')),
                ('subscription_details', models.TextField(blank=True, verbose_name='Details of subscriptions received from members (if any)')),
                ('has_bank_account', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('account_number', fernet_fields.fields.EncryptedCharField(blank=True, max_length=8, null=True, verbose_name='Account Number')),
                ('sort_code', fernet_fields.fields.EncryptedCharField(blank=True, max_length=6, null=True, verbose_name='Sort Code')),
                ('name_of_bank', models.CharField(blank=True, max_length=100, verbose_name='Name of Bank')),
                ('balance', models.CharField(blank=True, max_length=20, verbose_name='Rough Balance')),
                ('comments', models.TextField(blank=True, verbose_name='Comments')),
                ('treasurer_comments', models.TextField(blank=True, verbose_name='Treasurer Comments')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.Organization')),
            ],
        ),
        migrations.CreateModel(
            name='BudgetItem',
            fields=[
                ('entry_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(verbose_name='Description & Reasoning')),
                ('amount', models.CharField(max_length=20)),
                ('budget_type', models.IntegerField(choices=[(1, 'General'), (2, 'Cuppers'), (3, 'Exceptional')])),
                ('treasurer_comments', models.TextField(blank=True, verbose_name='Treasurer Comments')),
                ('budget', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='budget.Budget')),
            ],
        ),
    ]
