# Generated by Django 2.2.28 on 2024-09-19 16:18

import budget.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_manualadjustment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='president_crsid',
            field=budget.models.MultiCRSidField(max_length=30, verbose_name='CRSid'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='treasurer_crsid',
            field=budget.models.MultiCRSidField(max_length=30, verbose_name='CRSid'),
        ),
    ]
