# Generated by Django 2.2.28 on 2024-07-24 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
